/* Generated by Yosys 0.12+54 (git sha1 59a715034, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os) */

module spi_exe_unit_2_rtl(i_rst, i_sclk, i_mosi, o_miso, i_cs);
  input i_cs;
  input i_mosi;
  input i_rst;
  input i_sclk;
  output o_miso;
  assign o_miso = 1'hx;
endmodule
